---
PreCommit:

  ALL:
    problem_on_unmodified_line: warn

  TrailingWhitespace:
    enabled: true

  FileEncoding:
    description: Check text files are valid UTF-8
    enabled: true

  SingleNewlineAtEof:
    description: Check text files end with a single newline
    enabled: true

  Copyright:
    description: Check copyright notices are present and updated
    enabled: true

  YamlLint:
    enabled: true
    on_warn: fail

  Cppcheck:
    description: Lint C/C++ source files with cppcheck
    enabled: true
    required_executable: cppcheck
    flags:
      - --quiet
      - --language=c
      - --enable=all
      - --inline-suppr
      - --suppress=missingIncludeSystem
      - "--template={file}:{line}:{message}"
    include:
      - '**/*.c'
      - '**/*.h'

  ShellCheck:
    enabled: true
    on_warn: fail
    include:
      - large-tree-test
      - test.bats
