---
# Copyright © 2024 Matt Robinson
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: Build & test
on:
  push:
  pull_request:
  schedule:
    - cron: '30 12 * * 5'

permissions:
  contents: read

jobs:
  build:
    name: Build & test
    strategy:
      matrix:
        os:
          - ubuntu-24.04
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Bats
        run: sudo apt-get install bats

      - name: Build
        run: KCFLAGS=-fanalyzer make

      - name: Bats tests
        run: ./test.bats

      - name: Large tree test
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./large-tree-test
